# Generated by Django 5.1.3 on 2024-12-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Muallifning ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Muallifning familiyasi')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Vafot etgan sana')),
                ('biography', models.TextField(blank=True, null=True, verbose_name="Muallif haqida qisqa ma'lumot")),
            ],
        ),
    ]
