# Generated by Django 5.1.3 on 2024-12-01 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitobning nomi')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Nashr sanasi')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='Kitobning ISBN raqami')),
                ('genre', models.CharField(max_length=100, verbose_name='Kitob janri')),
                ('summary', models.TextField(blank=True, null=True, verbose_name="Kitob haqida qisqacha ma'lumot")),
                ('photo_of_book', models.ImageField(blank=True, null=True, upload_to='', verbose_name='kitob rasmini kiriting')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100, verbose_name='yozgan foydalanuvchi ismi')),
                ('Kitob bahosi', models.PositiveSmallIntegerField(verbose_name=10)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Sharh matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='new.book')),
            ],
        ),
    ]
